server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://localhost:3306/product-db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: debug
    org.springframework: info
